name: Feature request
description: Suggest an improvement for Drift CLI
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe the user value and expected behavior.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to accomplish?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe what you want Drift to do.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches or current workarounds.

  - type: textarea
    id: notes
    attributes:
      label: Additional context
